### ISSUE TITLE
Side chain flexion probabilities.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#217]
As mentioned in #215 , too many side chain flexions are happening during dock, including one flexion of a phenylalanine residue into a position where it clashes with nearby protein atoms, causing false positives in the docking of ligands too big for the binding pocket.

Here are the flexion probabilities from the data in the cited https://pubmed.ncbi.nlm.nih.gov/10737948/ :

[flexion probabilities.ods](https://github.com/primaryodors/primarydock/files/11129710/flexion.probabilities.ods)

As you can see, the probability of any given Phe residue flexing in any real world protein-ligand binding is 0.015. This means about one and a half percent of dock poses for random selections of protein and ligand should include any flexion whatsoever of any Phe residue.

The probability of any given Arg flexing is 0.0635. Since we know Arg6.59 always flexes in OR51E* activations by SCFAs, 100% of all OR51E* docks with agonist SCFAs should flex Arg6.59.

**Comment by ssepeq** [comment]
If each pose be limited to a predetermined number of flexions, binding residues could be selected by their pre-iteration umet potential ligand binding times their flex probability. Then those residues, and only those residues, would be allowed to flex during the dock iterations.

The proposed "flexion selection" algorithm can begin with a 60% chance that at least one side chain will flex. If it does, then there would be a 60% chance that a second side chain would flex, and so on. This will produce a curve nearly identical to figure 2 of the article.

**Comment by ssepeq** [comment]
After spot checking a sample dock file, there were 41 residues capable of interacting with the ligand, as indicated by the presence of PDB lines in the dock output. A binary flex/rigid on all binding residues equals 2^41 possible combinations, most of which have too many positive values.

For a dock with zero flexions, there is only one possible combination: all 41 side chains rigid.

For one flexion, there are 41 possibilities, which can be narrowed down by the algorithm.

For two flexions, there are 41*40 possibilities, or 1640. For three flexions, 41*40*39 = 63960. 15% of all dock poses will have even larger numbers of possibilities. Even though combinations can be narrowed down by flexion probability and unmet potential, the odds of getting the right combination by chance alone would be incredibly small.

It leads me to wonder how many poses will be required each dock in order to get at least one accurate result most of the time.

**Comment by primaryodors** [comment]
So this feature got broken.
