### ISSUE TITLE
❗ VERY Wrong.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#227]
What happened here?

![image](https://user-images.githubusercontent.com/106125032/231815901-200a0492-605d-4b74-8101-97d961a219c2.png)

```
bin/primarydock primarydock.config --prot pdbs/OR51/OR51E2.8f76.pdb --hydro --lig sdf/beta-ionone.sdf --pose 25 --appendprot --elim 999
```

**Comment by ssepeq** [comment]
This is related to #226 since it happens when hydrogenating a protein in the docker, as opposed to hydrogenating it first before docking with it. Some of the atoms get moved to coordinates that coincide with other atoms of the same residue.

`primarydock.cpp` has:
```
if (hydrogenate_pdb)
{
    int resno, endres = protein->get_end_resno();
    for (resno=1; resno<=endres; resno++)
    {
        AminoAcid* res = protein->get_residue(resno);
        if (res) res->hydrogenate();
    }
}
```

...while `interpreter.cpp` has:
```
else if (!strcmp(words[0], "HYDRO"))
{
    int resno, endres = p.get_end_resno();
    for (resno=1; resno<=endres; resno++)
    {
        AminoAcid* res = p.get_residue(resno);
        if (res) res->hydrogenate();
    }
}   // HYDRO
```

No idea why the second one works while the first one doesn't, but if running pepteditor on the protein first to hydrogenate it before calling primarydock, it works:

![image](https://user-images.githubusercontent.com/66374250/231904786-f60629cc-3698-4ab0-a4c4-17677e725852.png)

**Comment by primaryodors** [comment]
Try saving the hydrogenated protein to a temp file and reloading the temp PDB every pose (including the first pose) instead of reloading the original PDB and hydrogenating it each time.

**Comment by ssepeq** [comment]
That worked. Still not sure why the other way failed, but this allows hydrogenating the PDB in the dock itself.
