### ISSUE TITLE
Some code files are changing a lot, hot spots?

### ISSUE THREAD

**Issue by objarni** [primaryodors/primarydock#58]
Did a little source code analysis, inspired by the book "Your code as a crime scene". These are the 10 most changed files last 100 commits:

```[('src/classes/molecule.cpp', 99),
 ('src/molecule_test.cpp', 98),
 ('src/classes/atom.cpp', 94),
 ('src/classes/atom.h', 94),
 ('src/classes/constants.h', 94),
 ('src/classes/intera.cpp', 94),
 ('src/classes/point.cpp', 94),
 ('src/classes/point.h', 94),
 ('src/podock.cpp', 91),
 ('src/classes/molecule.h', 84)]
 ```
 
I know the source is very actively changing, but it does point towards molecule and atom classes being 'bug zones'. Does this align with your gut feeling @ssepeq ?

**Comment by ssepeq** [comment]
Very cool analytics! I like the term bug zones, it seems like a useful way to describe some of the more difficult parts of the app.

There is still a lot of buggy code unfortunately in the SMILES parser, and that would affect some of the files in the list. The atom and point files have had new functions added and I think a few bugs fixed. Probably similar for constants.h but instead of functions it would just be new constants. At this point I'm pretty confident in podock.cpp and intera.cpp, so while they may yet receive more changes, the core functionality appears to be sound.

Surprising that molecule.cpp did not make the list actually.

**Comment by objarni** [comment]
I agree on the `molecule.cpp` not showing up being surprising... I cropped the list at 10 items, so it might have shown up at position 11 ;)

"Bug zones" was a Freudian slip on my side - it's called 'hot zones' in the book, hehe!
